version: '2'

services:
  # web server
  glpi-apache:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
      args:
        APACHE_TAG: ${APACHE_TAG}
    container_name: Glpi-apache
    hostname: glpiapache
    volumes:
      # app folder
      - ./www:/webapp:z
      - ./docker/apache/vhost.conf:/usr/local/apache2/conf/extra/vhost.conf
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    working_dir: /webapp
    ports:
      # http port
      - 80:80
    links:
      - glpi-dbmysql
      - glpi-php
    networks:
      red:
        ipv4_address: 172.26.0.31
  #PHP
  glpi-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        PHP_TAG: ${PHP_TAG}
        GLPI_BRANCH: ${GLPI_BRANCH}
        GLPI_SOURCE: ${GLPI_SOURCE}
        CLONNING_METHOD: ${CLONNING_METHOD}
    container_name: Glpi-PHP
    hostname: glpiphp
    command: ["/opt/cliinstall.sh"]
    volumes:
      - ./www:/webapp:z
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ~/.ssh:/root/.ssh:z #Your Access ssh keys
    links:
      - glpi-dbmysql
    networks:
      red:
        aliases:
          - glpiphp
        ipv4_address: 172.26.0.32
        
  # database
  glpi-dbmysql:
    build: 
      context: ./docker/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_TAG: ${MYSQL_TAG}
    container_name: Glpi-MYSQL
    hostname: glpidb
    volumes:
      # hold the persisted data
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      red:
        aliases:
          - glpidb
        ipv4_address: 172.26.0.33
  glpi-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Glpi-Phpmyadmin
    hostname: glpiphpmyadmin
    links:
      - glpi-dbmysql
    ports:
        - 8081:80
    environment:
        PMA_USER: root
        PMA_PASSWORD: docker
        PMA_HOST: glpi-dbmysql
    networks:
      red:
        aliases:
          - glpiphpmyadmin
        ipv4_address: 172.26.0.34
      
volumes:
  db-data: {}
# In this section we defined the network interface
networks:
  red:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.26.0.0/24
# End of file
