version: '2'

services:
  # web server
  glpi-apache:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
      args:
        APACHE_TAG: ${APACHE_TAG}
        HOST_SERVER_NAME: ${HOST_SERVER_NAME}
        HOMEPATH: ${HOMEPATH}
    container_name: Glpi-apache
    hostname: glpiapache
    volumes:
      # app folder
      - ./www:${HOMEPATH}:z
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    working_dir: ${HOMEPATH}
    ports:
      # http port
      - ${HOST_SERVER_WEB_PORT}:80
    links:
      - glpi-dbmysql
      - glpi-php
    networks:
      red:
        ipv4_address: 172.26.0.31
  #PHP
  glpi-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        PHP_TAG: ${PHP_TAG}
        GLPI_DB_NAME_TEST: ${GLPI_DB_NAME_TEST}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DB_USER_ROOT: ${MYSQL_DB_USER_ROOT}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        GLPI_BRANCH: ${GLPI_BRANCH}
        GLPI_SOURCE: ${GLPI_SOURCE}
        CLONNING_METHOD: ${CLONNING_METHOD}
        HOMEPATH: ${HOMEPATH}
        DEFAULT_TIME_ZONE: ${DEFAULT_TIME_ZONE}
        FLYVEMDM_BRANCH: ${FLYVEMDM_BRANCH}
        FLYVEMDM_SOURCE: ${FLYVEMDM_SOURCE}
        FLYVEMDM_PATH: ${FLYVEMDM_PATH}
        FUSIONINVENTORY_BRANCH: ${FUSIONINVENTORY_BRANCH}
        FUSIONINVENTORY_SOURCE: ${FUSIONINVENTORY_SOURCE}
        FUSIONINVENTORY_PATH: ${FUSIONINVENTORY_PATH}
    container_name: Glpi-PHP
    hostname: glpiphp
    command: ["/opt/dev-tools/cliinstall.sh"]
    volumes:
      - ./www:${HOMEPATH}:z
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ${HOST_CONFIG_SSH_PATH}:/root/.ssh:z #Your Access ssh keys
    links:
      - glpi-dbmysql
      - glpi-mosquitto
    networks:
      red:
        aliases:
          - glpiphp
        ipv4_address: 172.26.0.32
  # database
  glpi-dbmysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_TAG: ${MYSQL_TAG}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: Glpi-MYSQL
    hostname: glpidb
    volumes:
      # hold the persisted data
      - ./db_data:/var/lib/mysql
    ports:
      - ${HOST_SERVER_DB_PORT}:3306
    networks:
      red:
        aliases:
          - glpidb
        ipv4_address: 172.26.0.33
  glpi-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Glpi-Phpmyadmin
    hostname: glpiphpmyadmin
    links:
      - glpi-dbmysql
    ports:
        - ${HOST_ADMIN_DB}:80
    environment:
        PMA_USER: root
        PMA_PASSWORD: docker
        PMA_HOST: glpi-dbmysql
    networks:
      red:
        aliases:
          - glpiphpmyadmin
        ipv4_address: 172.26.0.34
  # mosquitto
  glpi-mosquitto:
    build:
      context: ./docker/mosquitto
      dockerfile: Dockerfile
      args:
        MOSQUITTO_TAG: ${MOSQUITTO_TAG}
    container_name: Glpi-Mosquitto
    hostname: glpimosquitto
    links:
      - glpi-dbmysql
    volumes:
      # hold the persisted data
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - ${HOST_SERVER_MOSQUITTO_PORT}:1883
      - ${HOST_SERVER_MOSQUITTO_PORT_TLS}:8883
    networks:
      red:
        aliases:
          - glpimqtt
        ipv4_address: 172.26.0.35
volumes:
  db-data: {}
  mosquitto: {}
# In this section we defined the network interface
networks:
  red:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.26.0.0/24
# End of file
